// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migraties (met advisory locks) werken niet betrouwbaar via een pooler
    // (bv. Neon's pooled/PgBouncer-verbinding) — gebruik daarom bij voorkeur een
    // directe, ongepoolde connectie. Valt terug op DATABASE_URL als die niet apart is gezet.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
